USE gogetgro;

ALTER TABLE products
    ADD COLUMN IF NOT EXISTS stock_quantity INT NOT NULL DEFAULT 0;

DELETE FROM products;
DELETE FROM categories;

INSERT INTO categories (slug, name, icon_class, home_featured, home_sort) VALUES
('only-in-gogetgro', 'Only in GoGetGro', 'bi-star', 0, 1),
('fresh-produce', 'Fresh Produce', 'bi-brightness-high', 1, 5),
('fresh-meat-seafood', 'Fresh Meat & Seafood', 'bi-piggy-bank', 1, 6),
('frozen-goods', 'Frozen Goods', 'bi-snow', 1, 1),
('ready-to-cook', 'Ready to Cook', 'bi-fire', 0, 2),
('chilled-dairy', 'Chilled & Dairy Items', 'bi-thermometer-snow', 0, 3),
('bakery', 'Bakery', 'bi-cup-hot', 0, 4),
('international-goods', 'International Goods', 'bi-globe', 0, 5),
('pantry', 'Pantry', 'bi-box-seam', 1, 2),
('snacks', 'Snacks', 'bi-cookie', 0, 6),
('beverage', 'Beverage', 'bi-cup-straw', 1, 7),
('health-beauty', 'Health & Beauty', 'bi-heart-pulse', 1, 4),
('babies-kids', 'Babies & Kids', 'bi-gender-ambiguous', 0, 7),
('home-care', 'Home Care', 'bi-house-heart', 0, 8),
('pet-care', 'Pet Care', 'bi-heart', 0, 9),
('diy-hardware', 'DIY/Hardware', 'bi-tools', 0, 10),
('home-appliance', 'Home Appliance & Essentials', 'bi-tv', 0, 11),
('health-hygiene', 'Health & Hygiene Essentials', 'bi-shield-check', 1, 3);

INSERT INTO products (category_slug, name, price, image_path) VALUES
('only-in-gogetgro', 'GoDeals | Korean Kimbap Roll | per pack', 135.00, 'images/oigkimbap.jpg'),
('only-in-gogetgro', 'GoDeals | Premium Paper Towel (Long Roll) | per roll', 65.00, 'images/oigpapertowel.jpg'),
('only-in-gogetgro', 'GoDeals | Sliced Beef Strips | per 500g', 220.00, 'images/oigbeef.jpg'),
('only-in-gogetgro', 'GoDeals | Purified Drinking Water | per bottle', 25.00, 'images/oigwater.jpg'),
('only-in-gogetgro', 'GoDeals | Fruit Gummies | per pack', 89.00, 'images/oiggummies.jpg'),
('only-in-gogetgro', 'GoDeals | Creamy Peanut Butter | per jar', 175.00, 'images/oigpeanutbutter.jpg'),
('only-in-gogetgro', 'GoDeals | Premium Almonds | per pack', 220.00, 'images/oigalmonds.jpg'),
('only-in-gogetgro', 'GoDeals | Chocolate Almonds | per pack', 195.00, 'images/oigchocoalmonds.jpg'),
('only-in-gogetgro', 'GoDeals | Dried Mangoes | per pack', 160.00, 'images/oigdriedmangoes.jpg'),
('only-in-gogetgro', 'GoDeals | Black Hoodie | per piece', 499.00, 'images/oigblackhoodie.jpg'),
('only-in-gogetgro', 'GoDeals | Glass Storage Container | per piece', 249.00, 'images/oigglassstorage.jpg'),
('only-in-gogetgro', 'GoDeals | Sea Moss Supplement | per jar', 320.00, 'images/oigseamoss.jpg'),
('only-in-gogetgro', 'GoDeals | Chicken Broth | per pack', 110.00, 'images/oigchickenbroth.jpg'),
('only-in-gogetgro', 'GoDeals | Women’s Multivitamins | per bottle', 390.00, 'images/oigwomenvitamin.jpg'),
('only-in-gogetgro', 'GoDeals | Nut Trail Mix | per pack', 185.00, 'images/oigtrailmix.jpg'),
('only-in-gogetgro', 'GoDeals | Plantain Chips | per pack', 145.00, 'images/oigplantainchips.jpg'),
('only-in-gogetgro', 'GoDeals | Chili Sauce | per bottle', 120.00, 'images/oigchilisauce.jpg'),
('only-in-gogetgro', 'GoDeals | Artisan Popcorn | per pack', 135.00, 'images/oigartisanpopcorn.jpg'),
('only-in-gogetgro', 'GoDeals | Raw Kale Chips | per pack', 165.00, 'images/oigrawkalechips.jpg'),
('only-in-gogetgro', 'GoDeals | Truffle Sauce | per bottle', 295.00, 'images/oigtrufflesauce.jpg'),
('only-in-gogetgro', 'GoDeals | Bagel Pack (3 pcs) | per pack', 180.00, 'images/oigbagelpack3.jpg'),
('only-in-gogetgro', 'GoDeals | Raw Milk | per bottle', 140.00, 'images/oigrawmilk.jpg'),
('only-in-gogetgro', 'GoDeals | Balsamic Vinegar | per bottle', 210.00, 'images/oigbalsamicvinegar.jpg'),
('only-in-gogetgro', 'GoDeals | Coconut Yogurt | per cup', 125.00, 'images/oigcoconutyogurt.jpg'),
('only-in-gogetgro', 'GoDeals | Pure Maple Syrup | per bottle', 275.00, 'images/oigmaplesyrup.jpg'),
('fresh-produce', 'Fuji Apple Large | per piece', 35.00, 'images/apple.jpg'),
('fresh-produce', 'Lakatan Banana | 1kg', 95.00, 'images/banana.jpg'),
('fresh-produce', 'Fresh Carrots Local | 500g', 65.00, 'images/carrot.png'),
('fresh-produce', 'Red Onions | 1kg', 180.00, 'images/onion.jpg'),
('fresh-produce', 'Fresh Broccoli | 500g', 120.00, 'images/broccoli.jpg'),
('fresh-produce', 'Navel Orange Large | 3pcs', 110.00, 'images/orange.png'),
('fresh-produce', 'Calamansi (RS) approx. 1kg (Cebu)', 124.95, 'images/calamansi.jpg'),
('fresh-produce', 'Gabi Fruits (EP) approx. 400g', 60.00, 'images/gabi.jpg'),
('fresh-produce', 'Sweet Corn (CT) approx. 1.5kg', 179.93, 'images/corn.jpg'),
('fresh-produce', 'Papaya Green (CT) approx. 1kg', 59.95, 'images/papaya.jpg'),
('fresh-produce', 'Veggie Mix (LU) approx. 400g', 58.38, 'images/veggiemix.jpg'),
('fresh-produce', 'Rambutan (MPI) approx. 500g', 87.50, 'images/rambutan.jpg'),
('fresh-produce', 'Local Mixed Fruits (LEI) approx. 500g', 99.98, 'images/mixedfruits.jpg'),
('fresh-produce', 'Tomato Baguio approx. 600g', 233.55, 'images/tomato.jpg'),
('fresh-produce', 'Pinakbet Mix Vegetables (CT) approx. 1.2kg', 215.94, 'images/pinakbet.jpg'),
('fresh-produce', 'Yellow Capsicum (RS) approx. 300g', 272.99, 'images/capsicum.jpg'),
('fresh-produce', 'Peanuts with Shells (LEI) approx. 400g', 75.00, 'images/peanut.jpg'),
('fresh-produce', 'Linaga Mix (LEI) approx. 700g', 104.97, 'images/linaga.jpg'),
('fresh-produce', 'Aubergine Eggplant (CT) approx. 350g', 104.98, 'images/eggplant.jpg'),
('fresh-produce', 'Sampaloc Sigang approx. 200g', 30.99, 'images/sampalok.jpg'),
('fresh-produce', 'Cherry Tomato (RGPM) approx. 400g', 228.38, 'images/cherrytomato.jpg'),
('fresh-produce', 'Orange Sweet Potato approx. 600g', 98.97, 'images/sweetpotato.jpg'),
('fresh-produce', 'Celery approx. 400g', 159.98, 'images/celery.jpg'),
('fresh-produce', 'Ginger approx. 900g', 180.00, 'images/ginger.jpg'),
('fresh-produce', 'Green Muscat Grapes (RGPM) approx. 1kg', 868.95, 'images/grapes.jpg'),
('fresh-meat-seafood', 'Fresh Angus Ribeye Steak Cut 500g', 899.00, 'images/beef-ribeye.jpg'),
('fresh-meat-seafood', 'Fresh Pork Belly Slice (Liempo) 1kg', 420.00, 'images/pork-belly.jpg'),
('fresh-meat-seafood', 'Fresh Whole Chicken Farm Raised 1.2kg', 210.00, 'images/chicken-whole.jpg'),
('fresh-meat-seafood', 'Fresh Ground Beef Lean 500g', 275.00, 'images/ground-beef.jpg'),
('fresh-meat-seafood', 'Fresh Atlantic Salmon Fillet 300g', 520.00, 'images/salmon-fillet.jpg'),
('fresh-meat-seafood', 'Fresh Tilapia Whole Cleaned 1kg', 180.00, 'images/tilapia.jpg'),
('fresh-meat-seafood', 'Fresh Milkfish (Bangus) Medium Size 2pcs', 240.00, 'images/bangus.jpg'),
('fresh-meat-seafood', 'Fresh White Shrimp Medium Size 500g', 390.00, 'images/shrimp_fresh.jpg'),
('fresh-meat-seafood', 'Fresh Mud Crab Live Medium 1kg', 850.00, 'images/crab.jpg'),
('fresh-meat-seafood', 'Fresh Squid Tubes Cleaned 500g', 330.00, 'images/squid.jpg'),
('fresh-meat-seafood', 'Fresh Green Mussels (Tahong) 1kg', 160.00, 'images/mussels.jpg'),
('fresh-meat-seafood', 'Fresh Pork Chop Cut Bone-in 500g', 310.00, 'images/pork-chop.jpg'),
('fresh-meat-seafood', 'Fresh Beef Shank for Soup (Bulalo Cut) 1kg', 690.00, 'images/beef-shank.jpg'),
('fresh-meat-seafood', 'Fresh Chicken Breast Fillet Skinless 500g', 180.00, 'images/chicken-breast.jpg'),
('fresh-meat-seafood', 'Fresh Tuna Steak Cut 500g', 420.00, 'images/tuna-steak.jpg'),
('fresh-meat-seafood', 'Fresh Pork Minced Meat 500g', 195.00, 'images/pork-mince.jpg'),
('fresh-meat-seafood', 'Fresh Beef Strips for Tapa 500g', 345.00, 'images/beef-tapa.jpg'),
('fresh-meat-seafood', 'Fresh Chicken Wings Cut 1kg', 260.00, 'images/chicken-wings.jpg'),
('fresh-meat-seafood', 'Fresh Lapu-Lapu Whole Cleaned 700g', 780.00, 'images/lapu-lapu.jpg'),
('fresh-meat-seafood', 'Fresh Jumbo Prawns 500g', 620.00, 'images/prawns.jpg'),
('fresh-meat-seafood', 'Fresh Beef Brisket Slice 1kg', 720.00, 'images/beef-brisket.jpg'),
('fresh-meat-seafood', 'Fresh White Fish Fillet Boneless 500g', 250.00, 'images/fish-fillet.jpg'),
('fresh-meat-seafood', 'Fresh Pork Ribs Cut (Baby Back) 1kg', 480.00, 'images/pork-ribs.jpg'),
('fresh-meat-seafood', 'Fresh Salmon Head for Soup 500g', 210.00, 'images/salmon-head.jpg'),
('fresh-meat-seafood', 'Fresh Beef Cubes for Stew 500g', 360.00, 'images/beef-cubes.jpg'),
('frozen-goods', 'Great Earth Frozen Corn & Carrots 500g', 259.95, 'images/CornCarrot.jpg'),
('frozen-goods', 'Unagi Kabayaki Frozen Roasted Eel 199g', 510.00, 'images/eel.jpg'),
('frozen-goods', 'Great Earth Frozen Strawberries 2lbs', 389.95, 'images/strawberry.jpg'),
('frozen-goods', 'Virginia Frozen Corned Beef 1kg', 470.00, 'images/virginiabeef.jpg'),
('frozen-goods', 'Sarangani Bay Frozen Fish Fingers 200g', 135.00, 'images/fishfinger.jpg'),
('frozen-goods', 'Ocean Mama Frozen Butterfish IQF 1Lb', 199.95, 'images/butterfish.jpg'),
('frozen-goods', 'Swiss Deli Beef Hungarian Sausage 500g', 491.95, 'images/sausage.jpg'),
('frozen-goods', 'Great Earth French Fries Shoestring 2Lbs.', 175.00, 'images/fries.jpg'),
('frozen-goods', 'Magnolia Ube Keso Ice Cream 1.3L', 269.95, 'images/icecream1.jpg'),
('frozen-goods', 'Seoju Chocomallow Ice Cream Bar 8 x 75mL', 258.95, 'images/icecreambar1.jpg'),
('frozen-goods', 'Emborg Edamame Whole Green Soybeans 400g', 315.00, 'images/soybeans.jpg'),
('frozen-goods', 'UnMeat Plant-Based Nuggets 200g', 125.95, 'images/nuggets.jpg'),
('frozen-goods', 'Simplot Breaded Jalapeno with Cheese 908g', 835.95, 'images/jalapeno.jpg'),
('frozen-goods', 'Great Earth Potato Wedges 2Lbs.', 336.95, 'images/wedges.jpg'),
('frozen-goods', 'Espuna Tapas Fuet D Olot 60g', 560.95, 'images/tapas.jpg'),
('frozen-goods', 'SeaKing Marinated Hot Boneless Milkfish Bangus', 342.95, 'images/milkfish.jpg'),
('frozen-goods', 'Taiwan Balls Crab Fish Ball 750g', 489.95, 'images/crabfishball.jpg'),
('frozen-goods', 'Parklane Hashbrown Potatoes 637g', 224.95, 'images/Hashbrown.jpg'),
('frozen-goods', 'Dae Jang Gum Lumpia Wrapper Big 210g/pack', 47.00, 'images/Wrapper.jpg'),
('frozen-goods', 'Maks Recipes Pork Siomai', 596.95, 'images/Siomai.jpg'),
('frozen-goods', 'Fishing Village Cooked Shrimps 150-200lbs', 1049.95, 'images/shrimp.jpg'),
('frozen-goods', 'Purefoods Tender Juicy Classic Hotdog 1kg', 198.00, 'images/hotdog.jpg'),
('frozen-goods', 'Beef Salpicao (PM) approx. 700g', 419.97, 'images/beef.jpg'),
('frozen-goods', 'Purefoods Classic Honeycured Bacon 1kg', 718.50, 'images/bacon.jpg'),
('frozen-goods', 'Tuna Sashimi Plain 500g', 458.95, 'images/sashimi.jpg'),
('ready-to-cook', 'Pork Tocino Sweet Cure | 250g', 95.00, 'images/tocino.jpg'),
('ready-to-cook', 'Garlic Longganisa Native Style | 200g', 85.00, 'images/longganisa.jpg'),
('ready-to-cook', 'Purefoods Red Hotdogs | 500g', 120.00, 'images/hotdog.jpg'),
('ready-to-cook', 'Beef Tapa Marinated | 250g', 135.00, 'images/tapa.jpg'),
('ready-to-cook', 'CDO Corned Beef Classic | 150g', 55.00, 'images/cornedbeef.jpg'),
('ready-to-cook', '555 Sardines in Tomato Sauce | 155g', 28.00, 'images/sardines.jpg'),
('ready-to-cook', 'Chicken Adobo Cut Marinated | 500g', 160.00, 'images/adobo.jpg'),
('ready-to-cook', 'Pork Liempo Marinated BBQ Style | 500g', 210.00, 'images/liempo.jpg'),
('ready-to-cook', 'Marinated Chicken Wings BBQ | 500g', 175.00, 'images/chickenwing.jpg'),
('ready-to-cook', 'Pork Sisig Ready-to-Cook | 250g', 110.00, 'images/sisig.jpg'),
('ready-to-cook', 'Pork Lumpiang Shanghai Frozen | 500g', 180.00, 'images/shanghai.jpg'),
('ready-to-cook', 'Breaded Fish Fillet Frozen | 400g', 165.00, 'images/fishfillet.jpg'),
('ready-to-cook', 'Asado Siopao Frozen Pack | 6pcs', 140.00, 'images/siopao.jpg'),
('ready-to-cook', 'Beef Burger Patties Frozen | 500g', 190.00, 'images/burgerpatty.jpg'),
('ready-to-cook', 'Chicken Nuggets Crispy Frozen | 300g', 120.00, 'images/nuggets.jpg'),
('ready-to-cook', 'Frozen Meatballs Italian Style | 400g', 155.00, 'images/meatballs.jpg'),
('ready-to-cook', 'Daing na Bangus Marinated | 2pcs', 140.00, 'images/rotbangus.jpg'),
('ready-to-cook', 'Frozen Tilapia Cleaned | 1kg', 160.00, 'images/rottilapia.jpg'),
('ready-to-cook', 'Frozen Beef Empanada | 6pcs', 150.00, 'images/empanada.jpg'),
('ready-to-cook', 'Kikiam Street Food Style Frozen | 500g', 130.00, 'images/kikiam.jpg'),
('chilled-dairy', 'Lipa Fresh Coconut Juice 500mL', 76.95, 'images/coconutjuice.jpg'),
('chilled-dairy', 'Magnolia Butter-licious Unsalted Butter 200g', 97.00, 'images/butter.jpg'),
('chilled-dairy', 'Crisco All-Vegetable Shortening 453g', 299.25, 'images/crisco.jpg'),
('chilled-dairy', 'Emborg Mild White Cheddar Cheese 200g', 279.00, 'images/cheddar.jpg'),
('chilled-dairy', 'Australian Gold Creamy Brie Cheese 115 g', 199.95, 'images/brie.jpg'),
('chilled-dairy', 'Coca-Cola Original Taste 1.5L', 85.00, 'images/coke.jpg'),
('chilled-dairy', 'Nibou Yourgurt Fruity Pudding with Nata De Coco 33 x 35g', 299.95, 'images/fruitypudding.jpg'),
('chilled-dairy', 'Bounty Fresh Premium Eggs Large size 12s', 141.95, 'images/egg.jpg'),
('chilled-dairy', 'Nestle All-Purpose Cream 250mL', 69.75, 'images/allpurposecream.jpg'),
('chilled-dairy', 'Nestle Sour Cream 240 g', 150.00, 'images/sourcream.jpg'),
('chilled-dairy', 'Haagen-Dazs Belgian Chocolate Ice Cream 460mL', 468.95, 'images/icecream3.jpg'),
('chilled-dairy', 'Hersheys Chocolate Ice Cream Bar 7 x 53mL', 453.95, 'images/icebar.jpg'),
('chilled-dairy', 'Yakult Probiotics Drink 5 x 80mL', 45.50, 'images/yakult.jpg'),
('chilled-dairy', 'Dutch Mill Delight Probiotic Drink 400mL', 110.00, 'images/delight.jpg'),
('chilled-dairy', 'Cowhead Premium Chocolate Milk 1L', 125.25, 'images/chocomilk.jpg'),
('chilled-dairy', 'Soyfresh Natural Soya Milk Drink 1L', 85.00, 'images/soya.jpg'),
('chilled-dairy', 'Nestle Greek Flavored Yogurt 500 g', 293.00, 'images/greek.jpg'),
('chilled-dairy', 'Nestle Blissful Berry Mix Yogurt 4 x 110g', 196.00, 'images/berrymixyogurt.jpg'),
('chilled-dairy', 'Dutch Mill Strawberry Yogurt Drink 4 x 180mL', 80.95, 'images/dutchmill.jpg'),
('chilled-dairy', 'The Gutsy Captain Ginger & Lemon Kombucha 1L', 214.95, 'images/kombucha.jpg'),
('chilled-dairy', 'Tropicana Twister Regular Orange PET 1L', 57.95, 'images/orangejuice1.jpg'),
('chilled-dairy', 'Del Monte Four Seasons Juice Drink Promo Pack', 198.95, 'images/fourseasons.jpg'),
('chilled-dairy', 'Mogu Mogu Lychee Juice with Nata de Coco 320mL', 235.95, 'images/mogu.jpg'),
('chilled-dairy', 'Ocean Spray Cranberry x Raspberry Juice Drink', 325.95, 'images/cranberry.jpg'),
('chilled-dairy', 'Granini Banana Juice 1L', 230.95, 'images/bananajuice.jpg'),
('bakery', 'Gardenia Classic White Bread 600g', 55.00, 'images/bread.jpg'),
('bakery', 'Eng Bee Tin Premium Brown Tikoy Medium', 295.00, 'images/tikoy.jpg'),
('bakery', 'Euro Glaze Fondant Mini Doughnut 8 x 30g', 360.00, 'images/donut.jpg'),
('bakery', 'Tous Les Jours Butter Croissant 60g', 75.00, 'images/croissant.jpg'),
('bakery', 'Muffin Break Blueberry Muffin 80g', 65.00, 'images/muffin.jpg'),
('bakery', 'Einstein Bros. Bagels Everything Bagel 4pcs', 220.00, 'images/bagel.jpg'),
('bakery', 'Brioche Pasquier Soft Brioche Burger Buns 4pcs', 150.00, 'images/brioche.jpg'),
('bakery', 'Pan de Sal (GO) approx. 500g', 50.00, 'images/pandesal.jpg'),
('bakery', 'Dough and Co. US Chocolate Tres Leches', 272.00, 'images/tresletche.jpg'),
('bakery', 'Alec''s Artisan Sourdough approx. 900g', 159.00, 'images/sourdough.jpg'),
('bakery', 'Dough and Co. Custard Twist Roll', 199.00, 'images/custardroll.jpg'),
('bakery', 'Blueberry Cheesecake 6', 529.00, 'images/cheesecake.jpg'),
('bakery', 'Dough and Co. Caramel Pastel de Nata 5s', 284.00, 'images/pasteldenata.jpg'),
('bakery', 'Dough and Co. Egg Pie 820g', 380.00, 'images/eggpie.jpg'),
('bakery', 'Hungrypac Chocolate Crinkles 24s', 370.00, 'images/crinkles.jpg'),
('bakery', 'European Gourmet Triple Choco Cookie 6s', 360.00, 'images/chococookie2.jpg'),
('bakery', 'Ensaymada 6s', 219.00, 'images/ensaymada.jpg'),
('bakery', 'Nic''s Cinnamon Rolls 6s', 90.00, 'images/cinnamon.jpg'),
('bakery', 'Dough and Co. Red Bean Anpan 4s', 157.00, 'images/redbean.jpg'),
('bakery', 'Euro Classic Baguette', 136.00, 'images/baguette.jpg'),
('international-goods', 'Oreo Original Cookies Imported | 137g', 65.00, 'images/oreo.jpg'),
('international-goods', 'Nutella Hazelnut Spread Imported | 350g', 245.00, 'images/nutella.jpg'),
('international-goods', 'Kellogg’s Corn Flakes Imported | 250g', 180.00, 'images/kellogs.jpg'),
('international-goods', 'Honey Nut Cheerios Imported | 300g', 220.00, 'images/cheerios.jpg'),
('international-goods', 'Pringles Sour Cream & Onion | 158g', 120.00, 'images/pringles.jpg'),
('international-goods', 'Lay’s Classic Potato Chips Imported | 184g', 130.00, 'images/lays.jpg'),
('international-goods', 'Coca-Cola Original Imported Can | 330ml', 45.00, 'images/cocacola.jpg'),
('international-goods', 'Pepsi Cola Imported Can | 330ml', 42.00, 'images/pepsi.jpg'),
('international-goods', 'Red Bull Energy Drink Imported | 250ml', 95.00, 'images/redbull.jpg'),
('international-goods', 'Hershey’s Milk Chocolate Bar Imported | 43g', 55.00, 'images/hershey.jpg'),
('international-goods', 'KitKat Classic Imported | 4 Finger 41.5g', 60.00, 'images/kitkat.jpg'),
('international-goods', 'M&M’s Chocolate Candies Imported | 45g', 65.00, 'images/mms.jpg'),
('international-goods', 'Ferrero Rocher 3pcs Imported Box | 37.5g', 110.00, 'images/ferrero.jpg'),
('international-goods', 'Skippy Peanut Butter Imported | 340g', 195.00, 'images/skippy.jpg'),
('international-goods', 'Maggi Instant Noodles Imported | 79g', 35.00, 'images/maggi.jpg'),
('international-goods', 'Nissin Cup Noodles Imported | 70g', 40.00, 'images/nissin.jpg'),
('international-goods', 'SPAM Classic Luncheon Meat Imported | 340g', 260.00, 'images/spam.jpg'),
('international-goods', 'Toblerone Swiss Chocolate Imported | 100g', 145.00, 'images/toblerone.jpg'),
('international-goods', 'Jacobs Coffee Instant Imported | 200g', 210.00, 'images/jacobs.jpg'),
('international-goods', 'Lipton Yellow Label Tea Imported | 50 bags', 180.00, 'images/lipton.jpg'),
('pantry', 'Lucky Me Instant Pancit Canton Chilimansi | 80g', 39.99, 'images/Pancit.png'),
('pantry', 'Spam Lite 50% Less Fat Luncheon Meat 340g', 226.95, 'images/Spam.jpg'),
('pantry', 'Jasmine Rice Premium Grade 10kg', 678.95, 'images/Rice.jpg'),
('pantry', 'Silver Swan Soy Sauce 1.892L', 101.00, 'images/Soy Sauce.png'),
('pantry', 'Baguio Pure Coconut Oil 1Gal.', 799.99, 'images/coconutoil.jpg'),
('pantry', 'Heinz Tomato Squeeze Ketchup 570g', 197.95, 'images/ketchup.jpg'),
('pantry', 'Quaker Oats Quick Cook Oatmeal 800g', 134.95, 'images/oats.jpg'),
('pantry', 'Hunts Pork & Beans 390g', 53.95, 'images/beans.jpg'),
('pantry', 'Century Tuna Flakes Hot & Spicy 3 x 180g', 138.99, 'images/centurytuna.jpg'),
('pantry', 'Palermo Pure Olive Oil 3L', 1849.95, 'images/oliveoil.jpg'),
('pantry', 'Silver Swan Cane Vinegar 1.893L', 80.95, 'images/vinegar.jpg'),
('pantry', 'Indomie Mi Goreng Instant Noodles 5 x 85g', 89.95, 'images/goreng.jpg'),
('pantry', 'Ottogi Jin Ramen Spicy Instant Noodles 5 x 120g', 209.99, 'images/ramen.jpg'),
('pantry', 'Kirkland Signature Pink Salt Grinder with Refill', 534.95, 'images/salt.jpg'),
('pantry', 'Palermo Rainbow Peppercorns 165g', 299.95, 'images/pepper.jpg'),
('pantry', 'Wonderful Pepper & Garlic Pistachios 300g', 459.00, 'images/pistachios.jpg'),
('pantry', 'Red Onions (GO) approx. 800g', 300.95, 'images/redonion1.jpg'),
('pantry', 'Garlic Imported (RS) approx. 1.1kg (Cebu)', 318.95, 'images/garlic2.jpg'),
('pantry', 'Potato approx. 1.5kg', 216.00, 'images/potato.jpg'),
('pantry', 'Ritz Original Crackers 200g', 149.99, 'images/crackers.jpg'),
('pantry', 'Combos Cheddar Cheese Baked Crackers 178.6g', 188.95, 'images/combos.jpg'),
('pantry', 'Palermo Premium Honeycomb 454g', 429.95, 'images/honey.jpg'),
('pantry', 'Honey Stars Kids Cereal 450g', 253.00, 'images/cereal.jpg'),
('pantry', 'Doña Maria Jasponica Brown Rice 10kg', 1299.95, 'images/brownrice.jpg'),
('snacks', 'Lays Classic Potato Chips 180g', 89.95, 'images/lays.jpg'),
('snacks', 'Cadbury Dairy Milk Chocolate Bar 100g', 79.95, 'images/cadbury.jpg'),
('snacks', 'Oreo Original Vanilla Sandwich Cookies 9 x 27.6g', 78.95, 'images/oreo.jpg'),
('snacks', 'Movie Theater Butter Microwave Popcorn 3 x 78g', 149.95, 'images/popcorn.jpg'),
('snacks', 'Samjin Cheddar Cheese Pretzel 300g', 269.95, 'images/pretzel.jpg'),
('snacks', 'Party Mixed Snacks 1kg', 311.95, 'images/mixedsnacks.jpg'),
('snacks', 'Koko Krunch Cookie Cereal Bar 24 x 14.5g', 279.95, 'images/cerealbar.jpg'),
('snacks', 'Cheezy Curls Cheese Flavored Snack 300g', 219.95, 'images/cheezycurls.jpg'),
('snacks', 'Rise Buddy Seaweed Rice Snack 60g', 61.95, 'images/seaweed.jpg'),
('snacks', 'Skittles Fruit Snacks 42s', 1104.95, 'images/skittles.jpg'),
('snacks', 'Takis Fuego Rolled Tortilla Chips 280g', 349.95, 'images/takis.jpg'),
('snacks', 'Welchs Island Fruits Fruit Snacks 227g', 329.95, 'images/fruitsnack.jpg'),
('snacks', 'Mr. Ito Choco Chips 165g', 164.95, 'images/chocochip.png'),
('snacks', 'Brownies Cookie Chips 80g', 123.95, 'images/brownie.jpg'),
('snacks', 'Nabisco Chips Ahoy! Chunky Chocolate Chip', 269.95, 'images/chipsahoy.jpg'),
('snacks', 'Ruffles Cheddar & Sour Cream Potato Chips 170g', 156.95, 'images/ruffles.jpg'),
('snacks', 'Healthy Tropics 100% Natural Philippine Banana Chips 100g', 122.95, 'images/bananachips.jpg'),
('snacks', 'AriZona Green Tea Fruit Gummy Snacks 142g', 129.95, 'images/gummytea.jpg'),
('snacks', 'Pantoja Sansrival Chips in Canister 80g', 214.95, 'images/sansrival.jpg'),
('snacks', 'Doritos Smokin BBQ Tortilla Chips 190g', 156.95, 'images/doritos.jpg'),
('snacks', 'Edelyns Homemade Nuts Crunchy Garlic Chips 170g', 289.95, 'images/garlicchips.jpg'),
('snacks', 'Snack Pack Berry Blue Gel 4s 368g', 109.95, 'images/bluegel.jpg'),
('snacks', 'Nestle Crunch Snack 3 x 30g', 129.95, 'images/crunch.jpg'),
('snacks', 'Gerber Puffs Strawberry Apple Cereal Snack 42g', 254.95, 'images/babypuffs.jpg'),
('snacks', 'Quaker Chocolate Chip Oat Cookies Multipack 150g', 89.95, 'images/chipoat.jpg'),
('beverage', 'Coca-Cola Original Taste 1.5L', 85.00, 'images/coke.jpg'),
('beverage', 'Nestle Fresh Milk 1L', 105.00, 'images/milk.jpg'),
('beverage', 'Del Monte 100% Pineapple Juice 1L', 98.00, 'images/juice.jpg'),
('beverage', 'Nature''s Spring Mineral Water 6L', 110.00, 'images/water.jpg'),
('beverage', 'Nescafe Gold Intense 200g', 435.00, 'images/coffee.jpg'),
('beverage', 'C2 Green Tea Apple 500ml', 28.00, 'images/tea.jpg'),
('beverage', 'Red Bull Energy Drink, 4x250mL', 343.95, 'images/redbull.jpg'),
('beverage', 'Pocari Sweat Ion Supply Drink 2L', 172.50, 'images/pocari.jpg'),
('beverage', 'Prime Ice Pop Hydration Drink 500mL', 129.25, 'images/prime.jpg'),
('beverage', 'Mogu Mogu Lychee Juice with Nata de Coco 320mL', 235.95, 'images/mogu.jpg'),
('beverage', 'Granini Banana Juice 1L', 230.95, 'images/juice.jpg'),
('beverage', 'Del Monte Four Seasons Juice Drink Promo Pack', 198.95, 'images/fourseasons.jpg'),
('beverage', 'Lipa Fresh Coconut Juice 500mL', 76.95, 'images/coconutjuice.jpg'),
('beverage', 'Tropicana Twister Regular Orange PET 1L', 57.95, 'images/orangejuice1.jpg'),
('beverage', 'Dutch Mill Delight Probiotic Drink 400mL', 110.00, 'images/delight.jpg'),
('beverage', 'The Gutsy Captain Ginger & Lemon Kombucha 1L', 214.95, 'images/kombucha.jpg'),
('beverage', 'Ocean Spray Cranberry x Raspberry Juice Drink', 325.95, 'images/cranberry.jpg'),
('beverage', 'Dutch Mill Strawberry Yogurt Drink 4 x 180mL', 80.95, 'images/dutchmill.jpg'),
('beverage', 'Yakult Probiotics Drink 5 x 80mL', 45.50, 'images/yakult.jpg'),
('beverage', 'Cowhead Premium Chocolate Milk 1L', 125.25, 'images/chocomilk.jpg'),
('health-beauty', 'Pantene Hair Fall Control 450ml', 249.00, 'images/shampoo.jpg'),
('health-beauty', 'Vaseline Healthy Bright 400ml', 320.00, 'images/lotion.jpg'),
('health-beauty', 'Colgate Total Whitening 150g', 145.00, 'images/toothpaste.jpg'),
('health-beauty', 'Rexona Men Ice Cool 50ml', 115.00, 'images/deodorant.jpg'),
('health-beauty', 'Cetaphil Gentle Skin Cleanser 250ml', 465.00, 'images/cleanser.jpg'),
('health-beauty', 'Cream Silk Damage Control 350ml', 210.00, 'images/conditioner.jpg'),
('health-beauty', 'Biore UV Aqua Rich Watery Essence SPF 50+ PA++++ 50g', 495.00, 'images/sunscreen.jpg'),
('health-beauty', 'Neutrogena Oil-Free Acne Wash 200ml', 299.00, 'images/facewash.jpg'),
('health-beauty', 'Gillette Mach3 Turbo Razor with 8 Cartridges', 1499.95, 'images/razor.jpg'),
('health-beauty', 'Calvin Klein CK One Unisex Eau de Toilette 100ml', 1899.95, 'images/perfume.jpg'),
('health-beauty', 'Dove Deep Moisture Body Wash 500ml', 199.00, 'images/bodywash.jpg'),
('health-beauty', 'Safeguard Pure White Liquid Hand Soap 450mL', 149.95, 'images/handsoap.jpg'),
('health-beauty', 'Listerine Cool Mint Mouthwash 1L', 478.00, 'images/mouthwash.jpg'),
('health-beauty', 'LOreal Paris 4 Brown Hair Color', 479.00, 'images/haircolor.jpg'),
('health-beauty', 'OPI Nail Lacquer 15ml', 850.00, 'images/nailpolish.jpg'),
('health-beauty', 'Nivea Body Lotion 400ml', 250.00, 'images/bodylotion.jpg'),
('health-beauty', 'Schwarzkopf Gliss 4-in-1 Regeneration Bond-Building Hair Mask 400mL', 457.00, 'images/regeneration.jpg'),
('health-beauty', 'Olay Complete Sensitive Plus Face Moisturizer 2 x 177mL', 2495.00, 'images/olay.jpg'),
('health-beauty', 'Nenuco Baby Cologne Spray 240mL', 294.00, 'images/colone.jpg'),
('health-beauty', 'Nivea Extra Whitening Anti-Perspirant Spray 150 mL', 275.25, 'images/spray.jpg'),
('babies-kids', 'MamyPoko Pants Diapers Medium | 38pcs', 320.00, 'images/diapers.jpg'),
('babies-kids', 'Pampers Baby Dry Large | 32pcs', 310.00, 'images/diapers_l.jpg'),
('babies-kids', 'Baby Wipes Unscented Soft Pack | 80sheets', 65.00, 'images/bkwipes.jpg'),
('babies-kids', 'Nido 3+ Growing Up Milk Powder | 700g', 320.00, 'images/bkmilk.jpg'),
('babies-kids', 'Bear Brand Fortified Powder Milk | 300g', 135.00, 'images/bkmilk2.jpg'),
('babies-kids', 'Similac Infant Formula Stage 1 | 400g', 850.00, 'images/formula.jpg'),
('babies-kids', 'Cerelac Rice & Milk Cereal | 250g', 120.00, 'images/cerelac.jpg'),
('babies-kids', 'Gerber Baby Cereal Oatmeal | 227g', 165.00, 'images/cerelac2.jpg'),
('babies-kids', 'Johnson’s Baby Shampoo Gentle Care | 200ml', 115.00, 'images/babyshampoo.jpg'),
('babies-kids', 'Johnson’s Baby Soap Mild | 100g', 45.00, 'images/babysoap.jpg'),
('babies-kids', 'Johnson’s Baby Lotion Soft & Smooth | 200ml', 150.00, 'images/bklotion.jpg'),
('babies-kids', 'Johnson’s Baby Powder Classic | 200g', 120.00, 'images/powder.jpg'),
('babies-kids', 'Baby Feeding Bottles Set BPA-Free | 3pcs', 180.00, 'images/bottles.jpg'),
('babies-kids', 'Silicone Baby Pacifier Soft Comfort | 2pcs', 90.00, 'images/pacifier.jpg'),
('babies-kids', 'Baby Rattle Toys Set Educational | 5pcs', 250.00, 'images/toys.jpg'),
('babies-kids', 'Baby Teether Silicone Cooling Toy | 1pc', 110.00, 'images/teether.jpg'),
('babies-kids', 'Gerber Baby Snacks Puffs Banana | 42g', 95.00, 'images/snacks.jpg'),
('babies-kids', 'Kids Juice Apple Flavor Pack | 6x200ml', 120.00, 'images/bkjuice.jpg'),
('babies-kids', 'Milo Kids Biscuits Chocolate | 120g', 55.00, 'images/bkcookies.jpg'),
('babies-kids', 'Bear Brand Jr. School Milk Drink | 200ml', 25.00, 'images/schoolmilk.jpg'),
('home-care', 'Tide Powder Detergent Original | 1kg', 175.00, 'images/detergent.jpg'),
('home-care', 'Surf Powder Detergent Calamansi | 1.4kg', 135.00, 'images/surf.jpg'),
('home-care', 'Downy Fabric Conditioner April Fresh | 1.5L', 165.00, 'images/downy.jpg'),
('home-care', 'Zonrox Bleach Regular | 1L', 75.00, 'images/zonrox.jpg'),
('home-care', 'Mr. Clean Multi-Surface Cleaner | 500ml', 95.00, 'images/mrclean.jpg'),
('home-care', 'Pine-Sol Disinfectant Cleaner Original | 500ml', 140.00, 'images/pinesol.jpg'),
('home-care', 'Joy Dishwashing Liquid Lemon | 495ml', 95.00, 'images/joy.jpg'),
('home-care', 'Pril Dishwashing Liquid Aloe Vera | 400ml', 85.00, 'images/pril.jpg'),
('home-care', 'Kitchen Sponge Scrubber Set | 5pcs', 60.00, 'images/sponge.jpg'),
('home-care', 'Garbage Bags Heavy Duty Black | 20pcs', 90.00, 'images/trashbag.jpg'),
('home-care', 'Glade Air Freshener Lavender | 320ml', 120.00, 'images/hcairfreshener.jpg'),
('home-care', 'Domex Toilet Bowl Cleaner | 500ml', 85.00, 'images/toiletcleaner.jpg'),
('home-care', 'Kleenex Bathroom Tissue 2-Ply | 10 rolls', 160.00, 'images/hctissue.jpg'),
('home-care', 'Kitchen Paper Towels Multi-Purpose | 2 rolls', 110.00, 'images/paper.jpg'),
('home-care', 'Microfiber Mop Floor Cleaning Set | 1pc', 250.00, 'images/mop.jpg'),
('home-care', 'Soft Bristle Broom Indoor Use | 1pc', 140.00, 'images/broom.jpg'),
('home-care', 'Plastic Cleaning Bucket 10L Durable | 1pc', 180.00, 'images/bucket.jpg'),
('home-care', 'Rubber Cleaning Gloves Household Use | Pair', 55.00, 'images/hcgloves.jpg'),
('home-care', 'Baygon Insect Killer Spray Original | 300ml', 145.00, 'images/insect.jpg'),
('home-care', 'Alcohol Spray 70% Ethyl Sanitizer | 500ml', 95.00, 'images/hcsanitizer.jpg'),
('pet-care', 'Pedigree Adult Dog Food 1kg', 180.00, 'images/dogfood.jpg'),
('pet-care', 'Whiskas Ocean Fish Cat Food 1kg', 220.00, 'images/catfood.jpg'),
('pet-care', 'Pedigree Dentastix Dog Treats', 95.00, 'images/dogtreats.jpg'),
('pet-care', 'Temptations Cat Treats 85g', 120.00, 'images/cattreats.jpg'),
('pet-care', 'Saint Roche Dog Shampoo 250ml', 160.00, 'images/petshampoo.jpg'),
('pet-care', 'Madre de Cacao Pet Soap', 80.00, 'images/petsoap.jpg'),
('pet-care', 'Hartz Flea & Tick Powder', 210.00, 'images/flea_powder.jpg'),
('pet-care', 'Adjustable Nylon Dog Collar', 120.00, 'images/petcollar.jpg'),
('pet-care', 'Nylon Dog Leash 1.2m', 150.00, 'images/petleash.jpg'),
('pet-care', 'Orocan Plastic Pet Bowl', 70.00, 'images/petbowl.jpg'),
('pet-care', 'Automatic Pet Water Dispenser', 350.00, 'images/petwaterdispenser.jpg'),
('pet-care', 'Meowtech Cat Litter 5L', 180.00, 'images/littersand.jpg'),
('pet-care', 'Cat Litter Box with Scoop', 320.00, 'images/litterbox.jpg'),
('pet-care', 'Biodegradable Pet Waste Bags (Roll)', 90.00, 'images/poopbags.jpg'),
('pet-care', 'Pet Cleaning Wipes 80s', 140.00, 'images/petwipes.jpg'),
('pet-care', 'Rubber Dog Chew Toy', 110.00, 'images/dogtoy.jpg'),
('pet-care', 'Feather Teaser Cat Toy', 95.00, 'images/cattoy.jpg'),
('pet-care', 'Foldable Pet Cage Small', 850.00, 'images/cage.jpg'),
('pet-care', 'Pet Carrier Bag Medium', 600.00, 'images/carrier.jpg'),
('pet-care', 'LC-Vit Plus Multivitamins 60ml', 130.00, 'images/vitamins.jpg'),
('pet-care', 'Dr. Shiba Anti-Tick & Flea Soap', 90.00, 'images/ticksoap.jpg'),
('pet-care', 'Disposable Dog Diapers (10pcs)', 180.00, 'images/dogdiaper.jpg'),
('pet-care', 'Pet Training Pads 10pcs', 150.00, 'images/trainingpads.jpg'),
('pet-care', 'Basic Pet Grooming Kit', 280.00, 'images/groomingkit.jpg'),
('pet-care', 'Glade Pet Odor Eliminator Spray', 370.00, 'images/airfreshener.jpg'),
('diy-hardware', 'Lotus Claw Hammer 16oz', 320.00, 'images/hammer.jpg'),
('diy-hardware', 'Stanley Screwdriver Set 6pcs', 450.00, 'images/screwdriver.jpg'),
('diy-hardware', 'Ingco Measuring Tape 5m', 180.00, 'images/measuringtape.jpg'),
('diy-hardware', 'Lotus Adjustable Wrench 8-inch', 280.00, 'images/adjustablewrench.jpg'),
('diy-hardware', 'Ingco Combination Pliers 7-inch', 220.00, 'images/pliers.jpg'),
('diy-hardware', 'Stanley Hand Saw 20-inch', 350.00, 'images/handsaw.jpg'),
('diy-hardware', 'Davies Paint Brush 2-inch', 120.00, 'images/paintbrush.jpg'),
('diy-hardware', 'Boysen Paint Roller Set', 250.00, 'images/paintroller.jpg'),
('diy-hardware', 'Pioneer Electrical Tape Black', 35.00, 'images/electricaltape.jpg'),
('diy-hardware', 'Omni Extension Cord 4-Gang', 300.00, 'images/extensioncord.jpg'),
('diy-hardware', 'Firefly LED Bulb 9W', 130.00, 'images/ledbulb.jpg'),
('diy-hardware', 'Firefly Rechargeable Flashlight', 320.00, 'images/flashlight.jpg'),
('diy-hardware', 'Bosch Electric Drill 10mm', 2500.00, 'images/drill.jpg'),
('diy-hardware', 'Ingco Safety Gloves', 90.00, 'images/gloves.jpg'),
('diy-hardware', '3M Dust Mask (Pack of 2)', 120.00, 'images/mask.jpg'),
('diy-hardware', 'Rugby Silicone Sealant Clear', 180.00, 'images/silicone.jpg'),
('diy-hardware', 'Rugby Contact Cement 200ml', 95.00, 'images/rugby.jpg'),
('diy-hardware', 'Yale Padlock 40mm', 350.00, 'images/padlock.jpg'),
('diy-hardware', 'Omni Door Hinges 3-inch (Pair)', 75.00, 'images/hinges.jpg'),
('diy-hardware', 'Royu Light Switch Single', 85.00, 'images/switch.jpg'),
('diy-hardware', 'Royu Convenience Outlet', 95.00, 'images/outlet.jpg'),
('diy-hardware', 'Firefly Bulb Holder E27', 60.00, 'images/bulbholder.jpg'),
('diy-hardware', 'Bosny Spray Paint 400ml', 180.00, 'images/spraypaint.jpg'),
('diy-hardware', 'WD-40 Multi-Use Product 200ml', 220.00, 'images/wd40.jpg'),
('diy-hardware', 'Glade Automatic Air Freshener Spray', 370.00, 'images/airfreshener.jpg'),
('home-appliance', 'Asahi Electric Fan 16-inch', 1450.00, 'images/electricfan.jpg'),
('home-appliance', 'Imarflex Rice Cooker 1.5L', 1350.00, 'images/ricecooker.jpg'),
('home-appliance', 'Kyowa Electric Kettle 1.7L', 900.00, 'images/electrickettle.jpg'),
('home-appliance', 'Hanabishi Blender 1.5L', 1200.00, 'images/blender.jpg'),
('home-appliance', 'Philips Dry Iron Non-Stick', 850.00, 'images/flatiron.jpg'),
('home-appliance', 'Dowell Washing Machine 7kg Single Tub', 4800.00, 'images/washingmachine.jpg'),
('home-appliance', 'Sharp Microwave Oven 20L', 3500.00, 'images/microwave.jpg'),
('home-appliance', 'Condura Mini Refrigerator 3.5 cu.ft', 7800.00, 'images/refrigerator.jpg'),
('home-appliance', 'Royu Extension Cord 4-Gang with Switch', 280.00, 'images/extensioncord.jpg'),
('home-appliance', 'Firefly LED Bulb 9W', 130.00, 'images/ledbulb.jpg'),
('home-appliance', 'Firefly Rechargeable Flashlight', 320.00, 'images/flashlight.jpg'),
('home-appliance', 'Fujidenzo Water Dispenser Hot & Cold', 4200.00, 'images/waterdispenser.jpg'),
('home-appliance', 'Imarflex Induction Cooker', 1600.00, 'images/inductioncooker.jpg'),
('home-appliance', 'La Germania Single Burner Gas Stove', 950.00, 'images/gasstove.jpg'),
('home-appliance', 'Omni Universal Adapter Plug', 160.00, 'images/electricplug.jpg'),
('home-appliance', 'Asahi Floor Fan 18-inch', 1900.00, 'images/floorfan.jpg'),
('home-appliance', 'Kyowa Handheld Vacuum Cleaner', 1300.00, 'images/vacuum.jpg'),
('home-appliance', 'Hanabishi Air Cooler 10L', 3700.00, 'images/aircooler.jpg'),
('home-appliance', 'Jaguar Power Bank 10000mAh', 750.00, 'images/powerbank.jpg'),
('home-appliance', 'Orocan Digital Alarm Clock', 380.00, 'images/clock.jpg'),
('home-appliance', 'Asahi Wall Fan 16-inch', 1500.00, 'images/wallfan.jpg'),
('home-appliance', 'Firefly LED Desk Lamp', 480.00, 'images/lamp.jpg'),
('home-appliance', 'Kyowa 2-Slice Bread Toaster', 1050.00, 'images/toaster.jpg'),
('home-appliance', 'Imarflex Coffee Maker 0.6L', 1400.00, 'images/coffeemaker.jpg'),
('home-appliance', 'Glade Automatic Air Freshener Spray', 370.00, 'images/airfreshener.jpg'),
('health-hygiene', 'Green Cross Isopropyl Alcohol 70% | 500ml', 89.00, 'images/alcohol.jpg'),
('health-hygiene', 'Interfolded Paper Towel 175 Pulls', 45.00, 'images/tissue.jpg'),
('health-hygiene', 'Safeguard Liquid Hand Soap | 225ml', 120.00, 'images/handsoap.jpg'),
('health-hygiene', 'Colgate Total Toothpaste | 150g', 95.00, 'images/toothpaste.jpg'),
('health-hygiene', 'Oral-B Toothbrush Medium', 75.00, 'images/toothbrush.jpg'),
('health-hygiene', 'Head & Shoulders Shampoo Cool Menthol | 170ml', 145.00, 'images/shampoo.jpg'),
('health-hygiene', 'Cream Silk Conditioner Standout Straight | 180ml', 110.00, 'images/conditioner.jpg'),
('health-hygiene', 'Dove Deeply Nourishing Body Wash | 200ml', 160.00, 'images/bodywash.jpg'),
('health-hygiene', 'Celeteque Hydration Facial Wash | 100ml', 130.00, 'images/facewash.jpg'),
('health-hygiene', 'Lactacyd Feminine Wash | 150ml', 180.00, 'images/femininewash.jpg'),
('health-hygiene', 'Rexona Roll-On Deodorant Powder Dry | 50ml', 120.00, 'images/deodorant.jpg'),
('health-hygiene', 'Johnson''s Cotton Buds | 100 pcs', 65.00, 'images/cottonbuds.jpg'),
('health-hygiene', 'Swisspers Cotton Balls | 100 pcs', 90.00, 'images/cottonballs.jpg'),
('health-hygiene', 'Disposable Face Mask 3-Ply | 10 pcs', 70.00, 'images/facemask.jpg'),
('health-hygiene', 'Sanicare Baby Wipes Unscented | 80 pulls', 95.00, 'images/wetwipes.jpg'),
('health-hygiene', 'Whisper Regular Flow Sanitary Pads | 8 pcs', 85.00, 'images/sanitarypads.jpg'),
('health-hygiene', 'Carefree Pantyliners | 20 pcs', 75.00, 'images/pantyliner.jpg'),
('health-hygiene', 'Gillette Blue II Disposable Razor | 2 pcs', 110.00, 'images/razor.jpg'),
('health-hygiene', 'Hygienix Hand Gel Sanitizer | 50ml', 60.00, 'images/handgel.jpg'),
('health-hygiene', 'Listerine Cool Mint Mouthwash | 250ml', 180.00, 'images/mouthwash.jpg'),
('health-hygiene', 'Fissan Foot Powder | 50g', 70.00, 'images/footpowder.jpg'),
('health-hygiene', 'Band-Aid Adhesive Bandages | 20 pcs', 85.00, 'images/bandage.jpg'),
('health-hygiene', 'Hydrogen Peroxide Solution | 120ml', 50.00, 'images/hydrogenperoxide.jpg'),
('health-hygiene', 'Bioderm Germicidal Soap | 135g', 45.00, 'images/antibacterialsoap.jpg'),
('health-hygiene', 'Bath Loofah Scrubber', 55.00, 'images/loofah.jpg');

UPDATE products
SET stock_quantity = CASE
    WHEN MOD(id, 11) = 0 THEN 3
    WHEN MOD(id, 7) = 0 THEN 5
    WHEN MOD(id, 5) = 0 THEN 8
    WHEN MOD(id, 3) = 0 THEN 14
    ELSE 22
END;
